name: Main
env:
  CI: true
  FORCE_COLOR: 1
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.32.x
      - uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: 'pnpm'
      - run: pnpm install
      - run: pnpm run lint
      - run: pnpm run test
        env:
          PRIVATE_KEY: ${{secrets.PRIVATE_KEY}}
          ROOT_UCAN: ${{secrets.ROOT_UCAN}}
